site_name: Camel's Notebook
theme: 
  name: material
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  language: zh
  icon:
    logo: material/book-open-variant
    repo: fontawesome/brands/github
  favicon: images/camel.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit
    - content.action.view
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      lang: zh
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Camel-zy
repo_url: https://github.com/Camel-zy/Camel_Notebook
repo_name: Camel-zy/Camel_Notebook
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2023 Camel_zy